### ISSUE TITLE
Reset Rotation button does not handle globe roll correctly

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#370]
The reset rotation button is rolling the globe.  Initially the globe rolls more significantly, then with each subsequent button press, the roll amount decreases.  It should probably perform a full roll reset on first use, or not affect the roll at all and only reset the rotation.
[reset rotation.mp4.zip](https://github.com/ngageoint/opensphere/files/2713038/reset.rotation.mp4.zip)

**Comment by wallw-bits** [comment]
I believe this has been resolved in #420. @justin-bits can you confirm?

**Comment by justin-bits** [comment]
@wallw-bits, the initial behavior still exists as described. Still a valid bug.

**Comment by schmidtk** [comment]
I see what he's talking about, but it's very subtle and only when the camera is looking south of the equator. Probably related to `plugin.cesium.Camera#getCenter`, which is actually getting the 2D view center (code came from the original `ol-cesium` camera). If that's slightly different from the 3D center, it will cause the camera to move slightly.

**Comment by schmidtk** [comment]
That wasn't it. The behavior exists even when using the 3D camera center. I would guess `flyToBoundingSphere` isn't working quite how we expect.
